archives:
  - id: archive
    name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
    builds:
      - binary
builds:
  - binary: hh-responder
    id: binary
    dir: .
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - linux
    ldflags:
      - -w -s -X github.com/spigell/hh-responder/cmd.version={{.Tag}}
    main: .
changelog:
  use: github-native
release:
  disable: false
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
