name: The prebuilt binaries release

on:
  push:
    tags:
      - '*'


jobs:
  release:
    uses: spigell/my-shared-workflows/.github/workflows/golang-binary-release.yaml@main
    permissions:
      contents: write
    secrets:
      gh-token: ${{ secrets.GITHUB_TOKEN }}
