apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codex-home
  namespace: hh-responder-codex-workbench
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
