# This replace is used as an example for kustomize. And also for my homelab.


apiVersion: v1
kind: Pod
metadata:
  name: hh-responder-codex-workbench
  namespace: hh-responder-codex-workbench
spec:
  # NFS do not supports user namespaces.
  hostUsers: true
  volumes:
    - $patch: replace
    - name: project
      nfs:
        server: 192.168.1.48
        path: /home/spigell/projects/hh-responder
    - name: codex
      persistentVolumeClaim:
        claimName: codex-home
    - name: tmp
      emptyDir: {}
  containers:
    - name: workbench
      command: ["/bin/bash","-c","/project/deploy/develop/overrides/user-bootstrap.sh main"]
      securityContext:
        capabilities:
            drop: ["ALL"]
            add:
            - CHOWN
            - FOWNER
            - SETGID
            - SETFCAP
            - SETUID
            - DAC_OVERRIDE
      volumeMounts:
        - name: codex
          mountPath: /home/spigell/.codex
